[versions]
agp = "8.13.1"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.0"
composeBom = "2025.11.01"
hilt = "2.57.2"
coroutines = "1.10.2"
retrofit = "3.0.0"
logging = "5.3.2"
appCompat = "1.7.1"
material = "1.13.0"
constraintlayout = "2.2.1"
recyclerview = "1.4.0"
lifecycle = "2.10.0"
kotlinLib = "2.2.0"
fragmentKtx = "1.8.9"
hiltCompiler = "1.3.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-hilt = { group = "com.google.dagger", name = "hilt-android" , version.ref = "hilt"}
androidx-hilt-compliler = { group = "com.google.dagger", name = "hilt-compiler" , version.ref = "hilt"}
androidx-ahilt-compliler = { group = "androidx.hilt", name = "hilt-compiler" , version.ref = "hiltCompiler"}
androidx-hilt-android-compliler = { group = "com.google.dagger", name = "hilt-android-compiler" , version.ref = "hilt"}
androidx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core" , version.ref = "coroutines"}
androidx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android" , version.ref = "coroutines"}
androidx-retrofit = { group = "com.squareup.retrofit2", name = "retrofit" , version.ref = "retrofit"}
androidx-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson" , version.ref = "retrofit"}
androidx-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor" , version.ref = "logging"}
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat" , version.ref = "appCompat"}
androidx-material = { group = "com.google.android.material", name = "material" , version.ref = "material"}
androidx-constraint-layout = { group = "androidx.constraintlayout", name = "constraintlayout" , version.ref = "constraintlayout"}
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview" , version.ref = "recyclerview"}
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx" , version.ref = "lifecycle"}
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx" , version.ref = "lifecycle"}
androidx-kotlin-lib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib" , version.ref = "kotlinLib"}
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx" , version.ref = "fragmentKtx"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

